version: "3"
services:
  app:
    build: .
    depends_on:
      - mongo
    ports:
      - 8081:8081
    command: npm run dev
  mongo:
    image: mongo
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db
      - ./data/images:/data/images
      - ./data/epub:/data/epub
